spring:
  application:
    name: spring-security-jwt-exercise
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: verysecret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Jakarta
app:
  jwt:
    access-secret: wdgFBVS9P2joCLJ3eNmknbg3IXlkZBpMOgdpriotWH0=
    refresh-secret: OIGzn/d0OfjdLL4PhTgHLrv0Wme/Jvc2ls+VQI4cloQ=
    access-expiration: 15
    refresh-expiration: 1440
  cookie:
    secure: false
    max-age: 1440
